export type FlavorPhase = "thinking" | "tool" | "responding" | "stalled";

const FLAVOR_PACKS: Record<FlavorPhase, string[]> = {
	thinking: [
		"Accomplishing",
		"Calculating",
		"Cerebrating",
		"Pondering",
		"Cogitating",
		"Contemplating",
		"Considering",
		"Percolating",
		"Musing",
		"Inferring",
		"Deliberating",
		"Noodling",
		"Processing",
		"Thinking",
		"Imagining",
		"Ideating",
		"Computing",
		"Deciphering",
		"Determining",
		"Envisioning",
		"Philosophising",
		"Ruminating",
		"Mulling",
		"Puzzling",
		"Orchestrating",
		"Orbiting",
		"Astrogating",
		"Stargazing",
		"Mission-controlling",
		"Tricorder scanning",
		"Mind-melding",
		"Regenerating",
		"Code-raining",
		"Reality-bending",
		"Debugging",
		"Profiling",
		"Parsing",
		"Recursing",
	],
	tool: [
		"Actioning",
		"Architecting",
		"Skedaddling",
		"Tinkering",
		"Scurrying",
		"Wrangling",
		"Scampering",
		"Spelunking",
		"Crafting",
		"Forging",
		"Bootstrapping",
		"Recombobulating",
		"Processing",
		"Synthesizing",
		"Creating",
		"Crunching",
		"Propagating",
		"Reticulating",
		"Transfiguring",
		"Transmuting",
		"Dockerizing",
		"Kubernetizing",
		"Terraforming",
		"Refactoring",
		"Parsing",
		"Recursing",
		"Virtualizing",
		"Microservicing",
		"Debugging",
		"Deploying",
		"Compiling",
		"Linting",
		"Hotfixing",
		"Profiling",
		"Glitch-hunting",
		"Loot-farming",
		"Pixel-pushing",
		"Teleporting",
		"Wormholing",
		"Hyperdriving",
		"Quantumleaping",
		"Warp-driving",
		"Phasing",
		"Time-warping",
		"Nebula-hopping",
		"Photon-blasting",
		"Beaming-up",
		"Engaging",
		"Replicating",
		"Assembling",
		"Web-slinging",
		"Multiverse-hopping",
		"Arc reactor powering",
		"Vibranium-forging",
		"Rocket-launching",
		"Moon-landing",
		"Leveling-up",
		"Speedrunning",
	],
	responding: [
		"Composing",
		"Synthesizing",
		"Elucidating",
		"Crafting",
		"Creating",
		"Forming",
		"Determining",
		"Architecting",
		"Considering",
		"Actualizing",
		"Accomplishing",
		"Channeling",
		"Channelling",
		"Coalescing",
		"Concocting",
		"Generating",
		"Harmonizing",
		"Improvising",
		"Manifesting",
		"Orchestrating",
		"Transfiguring",
		"Transmuting",
		"Whirring",
		"Whisking",
		"Glimmering",
		"Sparkling",
		"Twinkling",
		"Jamming",
		"Freestyling",
		"Sampling",
		"Voguing",
		"Beatboxing",
		"Pixie-dusting",
		"Bibbidi bobbidi booing",
		"Launching to infinity",
		"Genie-wishing",
		"Prime Directive following",
		"Sonic-screwdriving",
		"Kung-fu-loading",
		"Flux-capacitating",
	],
	stalled: [
		"Simmering",
		"Stewing",
		"Mulling",
		"Waiting",
		"Percolating",
		"Roosting",
		"Holding",
		"Still working",
		"Lollygagging",
		"Meandering",
		"Nesting",
		"Puttering",
		"Billowing",
		"Ebbing",
		"Flowing",
		"Drifting",
		"Orbiting",
		"Stargazing",
		"Whiffling",
		"Bumbling",
		"Giggling",
		"Daydreaming",
		"Whimsy whirling",
		"Twinkling",
		"Whistling",
		"Swooning",
		"Galumphing",
		"Moonwalking",
	],
};

export function getFlavorText(phase: FlavorPhase, index: number): string {
	const pack = FLAVOR_PACKS[phase];
	if (!pack.length) {
		return "";
	}
	return pack[Math.abs(index) % pack.length] ?? "";
}

export function getFlavorCount(phase: FlavorPhase): number {
	return FLAVOR_PACKS[phase]?.length ?? 0;
}

export function getMinimalFlavorText(phase: FlavorPhase): string {
	switch (phase) {
		case "tool":
			return "Working";
		case "responding":
			return "Responding";
		case "stalled":
			return "Waiting";
		default:
			return "Thinking";
	}
}
